### ISSUE TITLE
Neural Voices

### ISSUE THREAD

**Issue by bazhabazha** [Femoon/tts-azure-web#1]
ms是改了吗，没找到带neural标签的声音啊，speech studio没有，走api也没有。

**Comment by Femoon** [comment]
没有理解你的意思，官方支持列表里多数语音已经带 neural 字符了，speech studio 可以看示例请求的代码

官方语音支持列表：https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/language-support?tabs=tts

Speech Studio 代码示例：
![image](https://github.com/user-attachments/assets/493fc444-e316-444a-9cad-18e5aa83a4fd)

**Comment by bazhabazha** [comment]
哦，代码里有，效果差强人意啊，跟elevenlabs比起来。

![Screenshot 2024-08-26 082905](https://github.com/user-attachments/assets/dae35f2a-418b-4d0f-a54f-7c6f7013c512)
