### ISSUE TITLE
这个项目是我用的所有文字转语音中最好的了，感谢👏。提一个建议，下载的时候除了 `.mp3` 加一个 `.srt` or `.lrc` 字幕文件

### ISSUE THREAD

**Issue by biolxy** [Femoon/tts-azure-web#3]

**Comment by Femoon** [comment]
谢谢建议，生成字幕文件在计划中

**Comment by wangfeng35** [comment]
+1，体验一级棒，感谢开发分享。
是否考虑增加个ssml直接生成的功能？

**Comment by Femoon** [comment]
> +1，体验一级棒，感谢开发分享。
> 
> 是否考虑增加个ssml直接生成的功能？

已增加 ssml 导入/导出功能

**Comment by Joshua19770704** [comment]
> > +1，体验一级棒，感谢开发分享。
> > 是否考虑增加个ssml直接生成的功能？
> 
> 已增加 ssml 导入/导出功能

但是导入SSML目前无法在多个人物和风格之间切换啊，能否直接增加个ssml 输入窗口呢？或者上传的话能够辨识整个ssml 文本，而不是现在这样只能识别第一个人物的？
