### ISSUE TITLE
有三个js文件比较大，加载特别慢

### ISSUE THREAD

**Issue by 9530045** [Femoon/tts-azure-web#5]
可能是我部署出现了问题，想请教一下，为什么我部署出来的会有这几个JS文件，而且还很大，很影响加载速度。
![image](https://github.com/user-attachments/assets/33947246-2ba2-437e-9218-afaae43ca3a8)

**Comment by Femoon** [comment]
感谢反馈，图中是开发环境，也就是执行 `pnpm dev` 的命令，所以部分 js 文件会比较大。

文档确实欠缺本地生产环境部署的命令，已经在文档中补充。

本地生产环境部署执行 `pnpm build` 和 `pnpm start` 来启动服务。启动后加载文件大小如下图

![image](https://github.com/user-attachments/assets/d2d09852-e66c-43b4-80ea-5495e32bb301)
