### ISSUE TITLE
在1.0.12版本中配置问题

### ISSUE THREAD

**Issue by 9530045** [Femoon/tts-azure-web#7]
![image](https://github.com/user-attachments/assets/16f87b37-bfa3-4200-bf60-2941bc8f5b73)
![image](https://github.com/user-attachments/assets/dcb39d38-5869-4883-b471-88740fa14db7)
![image](https://github.com/user-attachments/assets/2ebf4034-6a46-4aab-88cc-131b546a5cb3)

以上是本地部署出现的问题，想请教一下，到底是哪里除了问题呢？

**Comment by Femoon** [comment]
第一张图的新选项没有复现，重新拉取应该是没问题的。控制台的`script`路径`404`的问题是因为这两个脚本依赖`vercel`平台的数据统计，不影响功能，下个版本会修复
第二张图尝试`pnpm i`，如果报错依旧删除根目录的`node_modules`文件夹和`pnpm-lock.yaml`文件后执行`pnpm i`，再重新部署试试。

**Comment by 9530045** [comment]
![image](https://github.com/user-attachments/assets/438da013-1d9d-4d78-aa9d-91c1262ec112)
这样正常吗

**Comment by 9530045** [comment]
http://s.bangong.pro/

**Comment by 9530045** [comment]
这个时我的测试网站

**Comment by Femoon** [comment]
部署没有问题

新增的语音列表找到了官方博客：https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/new-hd-voices-preview-in-azure-ai-speech-contextual-and/ba-p/4258325

![image](https://github.com/user-attachments/assets/3a0a8b20-ac9b-46b2-bfbb-ed0ca3c31913)

看博客目前还没有在列表中加入，可能你的账户或者地区正好灰度到了？
 key 区域是什么，晚上我看看能不能适配下

**Comment by 9530045** [comment]
区域是东亚

**Comment by 9530045** [comment]
eastasia

**Comment by 9530045** [comment]
能适配吗？

**Comment by Femoon** [comment]
> 能适配吗？
> 
> 

最近实在太忙了，明后天适配下

**Comment by Femoon** [comment]
抱歉，回复晚了，东亚不在官方的计划区域内，之前显示的应该是错误的，现在看到东亚地区官方的 API 已经移除了。想用新的语音东南亚(southeastasia)上新了一个，请求时间有点长，等官方完善后适配

**Comment by 9530045** [comment]
好的，感谢你的解答
